services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '9000:9000'
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://admin:flooder22@mongodb:27017/hotel?authSource=admin
    command: npm run start:dev
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: flooder22
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo_express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: flooder22
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: flooder22
    ports:
      - '8081:8081'
    depends_on:
      - mongodb

volumes:
  mongo_data:
