services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db # Используем именованный том для данных MongoDB
    ports:
      - '${MONGO_PORT:-27017}:27017' # Порт с использованием значения по умолчанию, если переменная не определена

  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo_express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb # Устанавливаем сервер как "mongodb" для использования Docker-сети
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD}
    ports:
      - '8081:8081'
    depends_on:
      - mongodb

volumes:
  mongo_data:
